### ISSUE TITLE
pipeline dynamic state count value is incorrect

### ISSUE THREAD

**Issue by duarm** [PaoloMazzon/Vulkan2D#1]
tried to run the example and got a
```
vkCmdDraw: VkPipeline 0xd897d90000000016[] doesn't set up VK_DYNAMIC_STATE_SCISSOR, but it calls the related dynamic
state setting commands The Vulkan spec states: There must not have been any calls to dynamic state setting commands for any state not specified as dynamic in the VkPipeline object bound to the pipeline bind point used by this command, since that pipeline was bound
```
the problem was because the stateCount was 2 instead of 3, the dynamic state scissors wasn't being created.
```c
                const uint32_t stateCount = 2;
		VkDynamicState states[] = {
				VK_DYNAMIC_STATE_LINE_WIDTH,
				VK_DYNAMIC_STATE_VIEWPORT,
				VK_DYNAMIC_STATE_SCISSOR
		};
```
is this intended? I'm new to Vulkan

And thanks for making this, i'm learning a lot by looking at the source code.

**Comment by PaoloMazzon** [comment]
Thanks for pointing this out, you are correct. My debug layers weren't catching the dynamic scissor being disabled but when I swapped the position of viewport and scissors in that array the debug layer did catch it. Either way its been fixed.
