### ISSUE TITLE
Lack of documentation 

### ISSUE THREAD

**Issue by Germ210** [PaoloMazzon/Vulkan2D#14]
Hello there, I was wanting to ask about the documentation as there is very little (basic general overview and cameras). I will admit that I am not a C programmer, so I think that proper documentation would get me and more people more comfortable with the library without having to read code that they don't understand.

**Comment by PaoloMazzon** [comment]
Hi, I could definitely add some more overview stuff as what's visible on Github is limited. That said, the entire source is documented and if you run `$ doxygen` inside a cloned `Vulkan2D/` directory it will generate the complete documentation in another folder `html/` for the project where all structs, functions, and macros are documented.
![image](https://github.com/user-attachments/assets/4c40a11a-1722-42c4-8551-8a1dc1eedca3)

**Comment by Germ210** [comment]
That is true, however I currently don't have access to a computer which can clone the repository (I am currently on an android phone), and I do think that good documentation on the GitHub could bring more people in.

**Comment by PaoloMazzon** [comment]
It's not a bad idea and for that reason I just improved the documentation and now have it automatically set up to publish the current version of documentation at [https://paolomazzon.github.io/Vulkan2D/index.html](https://paolomazzon.github.io/Vulkan2D/index.html). It's got some bugs at the moment but the documentation is all there.

**Comment by Germ210** [comment]
Thank you
