### ISSUE TITLE
Integrating DearImGui with VK2D

### ISSUE THREAD

**Issue by Nolram12345** [PaoloMazzon/Vulkan2D#15]
Hello! 
I'm currently trying to integrate dearimgui into a Vulkan2D based project, with... mixed success. 
As per the [ImGui instructions](https://github.com/ocornut/imgui/wiki/Getting-Started#example-if-you-are-using-sdl2--vulkan), I've included the SDL2 and Vulkan backends, and placed the API functions as follows:

Imgui Init -> After _vk2dRendererInit_, passing the init_info as follows:
```c
ImGui_ImplVulkan_InitInfo init_info = {};
VK2DRenderer renderer = vk2dRendererGetPointer();
init_info.Instance = renderer->vk;
init_info.PhysicalDevice = renderer->pd->dev;
init_info.Device = renderer->ld->dev;
init_info.QueueFamily = renderer->pd->QueueFamily.graphicsFamily;
init_info.Queue = renderer->ld->queue;
init_info.PipelineCache = VK_NULL_HANDLE;
init_info.DescriptorPool = renderer->samplerPool;
init_info.Subpass = renderer->targetSubPass;
init_info.MinImageCount = renderer->swapchainImageCount;
init_info.ImageCount = renderer->swapchainImageCount;
init_info.MSAASamples = VK_SAMPLE_COUNT_1_BIT;
init_info.Allocator = NULL;
init_info.CheckVkResultFn = check_vk_result;
init_info.RenderPass = renderer->renderPass;
```
_ImGui_ImplSDL2_ProcessEvent_ -> Into the SDL2 PollEvents while loop,
ImGui (and SDL/Vulkan implementation) new frame functions -> after vk2dRendererStartFrame,
_ImGui::Render_ and _ImGui_ImplVulkan_RenderDrawData_ -> before _vk2dRendererEndFrame_, passing `vk2dRendererGetPointer()->commandBuffer` to the RenderDrawData.

However, it seems that ImGui doesn't draw to all the swapchain images correctly, and I'm not sure why, since I'm passing the imagecount directly from the render engine.
The visual output looks like this:
https://github.com/user-attachments/assets/0e4696bc-f96b-46de-a201-fcd19a47ee26

There is also an issue wherein the colourspace between ImGui and VK2D doesn't match, but that's the lesser issue in this case :)

I would appreciate any advice or recommendations/pointers as to what could be causing this and how I could address it. I've tested this with all the window mode (Vsync) options, and this occurs on all of them.

Thank you for your awesome work on VK2D!

**Comment by PaoloMazzon** [comment]
Hi, I appreciate the kind words! I haven't gotten around to implementing imgui myself so I'm not overly familiar with the process but I have a few guesses. I don't know your event loop but that kind of looks like it may be rendering to only one of the swapchain images. Also, `renderer->samplerPool` is made for the texture sampler while from what I can tell imgui requires a combined image sampler (which VK2D doesn't use). Its best to make your own descriptor pool for that as I don't think doing that is Vulkan compliant and would cause issues on some devices. When I have some time later I can try implementing imgui on my own to find the common pitfalls. Actually also double check that your MSAA value matches what VK2D is using. As for for the colour space issues, I know that is a common problem with imgui and I'm gonna need to look into it a little bit and get back to that.

P.S. While accessing the renderer directly works I highly recommend using [VulkanInterface.h](https://paolomazzon.github.io/Vulkan2D/VulkanInterface_8h.html) instead for readability and future-proofing purposes. The renderer is not meant to be user accessed and I've got no promises on it remaining structured that way long term lol.

**Comment by Nolram12345** [comment]
Thank you! I'll try again with the Vulkan Interface and see if I manage to get it to work (my Vulkan experience is a bit limited so I'm not certain I'll get it to function). An official implementation would of course be awesome, since ImGui is a pretty essential tool nowadays.
Yeah, I expected it to be a swapchain issue. My event loop is essentially just the one of the basic example in the readme.
As for the combined image sampler, should I attempt to create a new pool for it? 

Thank you for your help!

**Comment by Nolram12345** [comment]
I actually managed to get it to work by swapping my erroneous usage of `vk2dRendererGetPointer()->commandBuffer` on the _ImGui_ImplVulkan_RenderDrawData_ function with _vk2dVulkanGetDrawBuffer()_. Now only the SRGB issue remains, as well my incorrect usage of the sampler pool. I'll do some research myself.

**Comment by Nolram12345** [comment]
Worked around the SRGB issue by adding an SRGB->Linear converstion at the end of ImGui's fragment shader.
Another pitfall I encountered was that on Windows, SDL2 by default doesn't DPI-scale correctly on large displays.
One is required to call the windows,h `SetProcessDPIAware();` and add `SDL_WINDOW_ALLOW_HIGHDPI` flag to the SDL window.

**Comment by PaoloMazzon** [comment]
Hi, I was just looking into the sRGB problems and I found another solution to the colorspace problem that is less invasive than what you are doing, but I don't have time to get around to that solution quite yet (I wrote it down, I would like to support imgui out of the box). In the meantime that is a great solution that I'm happy to hear you've solved. As for SDL2's DPI scaling, I am aware of this and I have heard, without substantial evidence, that `SetProcessDPIAware();` isn't the best solution (although it works well for me) but in either case you reminded me to add an application manifest to the Windows version that should solve that in the near future. Also for the descriptor pool imgui wants, I found [this issue](https://github.com/ocornut/imgui/issues/4115) and also [vkguide](https://vkguide.dev/docs/new_chapter_2/vulkan_imgui_setup/) seems to corroborate it, you can create the descriptor pool imgui needs with something like

```c
vkDescriptorPoolSize pool_sizes[] = { { VK_DESCRIPTOR_TYPE_SAMPLER, 1000 },
	{ VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 1000 },
	{ VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, 1000 },
	{ VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, 1000 },
	{ VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER, 1000 },
	{ VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER, 1000 },
	{ VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, 1000 },
	{ VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1000 },
	{ VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC, 1000 },
	{ VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC, 1000 },
	{ VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT, 1000 } };

VkDescriptorPoolCreateInfo pool_info = {};
pool_info.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
pool_info.flags = VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT;
pool_info.maxSets = 1000;
pool_info.poolSizeCount = (uint32_t)std::size(pool_sizes);
pool_info.pPoolSizes = pool_sizes;

VkDescriptorPool imguiPool;
VK_CHECK(vkCreateDescriptorPool(_device, &pool_info, nullptr, &imguiPool));
```
(This code is from vkguide.dev)
I think 1000 per descriptor type is serious overkill but will probably work just fine and more importantly won't give you weird unexplainable crashes on more restrictive Vulkan drivers like the ones AMD devices tend to have.

Thanks for bringing this up and good luck on the project!
