### ISSUE TITLE
uniform buffers recreation is resetting all camera, even those who were not created

### ISSUE THREAD

**Issue by duarm** [PaoloMazzon/Vulkan2D#2]
When recreating the uniform buffers while resetting the swapchain, we recreate all cameras which are on the `cs_Reset` state.

```c
void _vk2dRendererCreateUniformBuffers(bool newCamera) {
        ...
	if (newCamera) { // If the renderer has not yet been initialized
        ...
	} else {
		// Recreate camera buffers with new screen
		for (int i = 0; i < VK2D_MAX_CAMERAS; i++) {
			if (gRenderer->cameras[i].state == cs_Reset) {
				gRenderer->cameras[i].state = cs_Deleted;
				vk2dCameraCreate(gRenderer->cameras[i].spec);
			}
		}
	}
       ...
```

but when we destroy the uniform buffers with `_vk2dRendererDestroyUniformBuffers`, we set ALL cameras to `cs_Reset`

```c
void _vk2dRendererDestroyUniformBuffers() {
	VK2DRenderer gRenderer = vk2dRendererGetPointer();
	uint32_t i;
	for (i = 0; i < VK2D_MAX_CAMERAS; i++)
		vk2dCameraSetState(i, cs_Reset);
	vk2dBufferFree(gRenderer->unitUBO);
}
```

If we resize the screen, all cameras are created, and if we resize before creating our own cams,  `vk2dCameraCreate` will always return -1. `_vk2dRendererDestroyUniformBuffers` should only reset the cameras which were on the cs_Normal/cs_Disabled state.

**Comment by PaoloMazzon** [comment]
Thanks for pointing this out, you're totally correct and I pushed a potential fix to `dev` which I will test and push to master when I can.
