### ISSUE TITLE
compile error when build examples/instancing/main.c

### ISSUE THREAD

**Issue by aiffc** [PaoloMazzon/Vulkan2D#5]
i get an error when compile examples, I think you should modify the function name in this file.

Vulkan2D/examples/instancing/main.c:40:21: error: conflicting types for ‘random’; have ‘float(float,  float)’
   40 | static inline float random(float min, float max) {
      |                     ^~~~~~
In file included from /usr/include/SDL2/SDL_stdinc.h:46,
                 from /usr/include/SDL2/SDL_video.h:31,
                 from /usr/include/SDL2/SDL_vulkan.h:31,
                 from /home/aif/codes/Vulkan2D/examples/instancing/main.c:2:
/usr/include/stdlib.h:402:17: note: previous declaration of ‘random’ with type ‘long int(void)’
  402 | extern long int random (void) __THROW;
      |                 ^~~~~~

**Comment by PaoloMazzon** [comment]
Hi thank you for pointing this out, I didn't get this error on my machine. That function is a bit of an oversight, I removed it all together because VK2D has its own atomic random it should be using instead.
